/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/drums.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder009.geometry} material={materials['default']} position={[-1.17, 0.07, -0.53]} rotation={[2.49, 0, -Math.PI]} scale={[0, 0.12, 0]} />
      <mesh geometry={nodes.Cylinder008.geometry} material={materials['default']} position={[-1.32, 0.42, 0.07]} scale={[0.14, 0.02, 0.14]} />
      <mesh geometry={nodes.hihatstand000.geometry} material={materials['default']} position={[-1.32, 0.23, 0.13]} scale={[1, 0.54, 1]} />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials['default']} position={[-0.78, 0.07, 0.43]} rotation={[2.49, 0, -Math.PI]} scale={[0, 0.12, 0]} />
      <mesh geometry={nodes.Cylinder006.geometry} material={materials['default']} position={[-0.55, 0.07, -0.21]} rotation={[0.65, 0, 0]} scale={[0, 0.12, 0]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['default']} position={[-1.22, 0.71, -0.3]} scale={[0.18, 0.02, 0.18]} />
      <mesh geometry={nodes.hightom001.geometry} material={materials['default']} position={[-0.85, 0.71, 0.28]} rotation={[-0.29, 0, 0]} />
      <mesh material-color={props.customColors.face} geometry={nodes.hightomdrumr.geometry} material={materials['default']} position={[-0.78, 0.71, -0.09]} rotation={[0.26, 0, 0]} scale={[1.11, 1, 1.08]} />
      <mesh material-color={props.customColors.face} geometry={nodes.bassdrum.geometry} material={materials['default']} position={[-0.77, 0.27, 0.11]} rotation={[0, 0, -Math.PI / 2]} scale={[1.78, 0.6, 1.72]} />
      <mesh geometry={nodes.hihatstand001.geometry} material={materials['default']} position={[-1.15, 0.74, -0.03]} rotation={[0.54, -0.01, -1.56]} scale={0.02} />
      <mesh material-color={props.customColors.chords} geometry={nodes.Circle003.geometry} material={materials['default']} position={[-1.14, 0.75, -0.55]} rotation={[0.02, 0, -Math.PI]} scale={[0.16, 0.84, 0.16]} />
      <mesh geometry={nodes.basstotops.geometry} material={materials['default']} position={[-0.66, 0.53, 0.12]} scale={0.11} />
      <mesh material-color={props.customColors.chords} geometry={nodes.Circle008.geometry} material={materials['default']} position={[-0.75, 0.99, -0.51]} rotation={[0.39, 0, -Math.PI]} scale={[0.16, 0.84, 0.16]} />
      <mesh material-color={props.customColors.chords} geometry={nodes.Circle007.geometry} material={materials['default']} position={[-0.75, 0.96, -0.55]} rotation={[0.54, -0.01, -1.56]} scale={[0.02, 0.01, 0.02]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials['default']} position={[-0.75, 0.82, -0.69]} rotation={[0.81, 0, 0]} scale={[0, 0.18, 0]} />
      <mesh geometry={nodes.crash2stand.geometry} material={materials['default']} position={[-0.75, 0.74, -0.68]} rotation={[0.54, -0.01, -1.56]} scale={0.02} />
      <mesh material-color={props.customColors.chords} geometry={nodes.Circle.geometry} material={materials['default']} position={[-0.75, 1.02, 0.52]} rotation={[-0.24, 0, -Math.PI]} scale={[0.19, 1, 0.19]} />
      <mesh geometry={nodes.crash1stand.geometry} material={materials['default']} position={[-0.75, 0.77, 0.53]} rotation={[0.54, -0.01, -1.56]} scale={0.02} />
      <group position={[-0.77, 0.27, 0.11]} rotation={[0, 0, -Math.PI / 2]} scale={[1.78, 0.6, 1.72]}>
        <mesh geometry={nodes.Cylinder004_1.geometry} material={materials['default']} />
        <mesh geometry={nodes.Cylinder004_2.geometry} material={materials['default']} />
        <mesh geometry={nodes.Cylinder004_3.geometry} material={materials['default']} />
      </group>
      <group position={[-1.24, 0.45, 0.47]}>
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['default']} />
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['default']} />
        <mesh geometry={nodes.Cylinder001_3.geometry} material={materials['default']} />
      </group>
      <group position={[-0.78, 0.71, -0.09]} rotation={[0.26, 0, 0]} scale={[1.11, 1, 1.08]}>
        <mesh geometry={nodes.Cylinder014.geometry} material={materials['default']} />
        <mesh geometry={nodes.Cylinder014_1.geometry} material={materials['default']} />
        <mesh geometry={nodes.Cylinder014_2.geometry} material={materials['default']} />
      </group>
      <group position={[-0.85, 0.71, 0.28]} rotation={[-0.29, 0, 0]}>
        <mesh geometry={nodes.Cylinder005.geometry} material={materials['default']} />
        <mesh geometry={nodes.Cylinder005_1.geometry} material={materials['default']} />
        <mesh geometry={nodes.Cylinder005_2.geometry} material={materials['default']} />
      </group>
      <group position={[-1.22, 0.72, -0.3]} scale={[0.18, 0.02, 0.18]}>
        <mesh geometry={nodes.Cylinder003.geometry} material={materials['default']} />
        <mesh geometry={nodes.Cylinder003_1.geometry} material={materials['default']} />
        <mesh geometry={nodes.Cylinder003_2.geometry} material={materials['default']} />
        <mesh geometry={nodes.Cylinder003_3.geometry} material={materials['default']} />
      </group>
    </group>
  )
}

useGLTF.preload('/drums.glb')
