/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef,useState } from 'react'
import { useGLTF,Text } from '@react-three/drei'


export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/exemple1.glb')
  
  const [text, setText] = useState(false)
  console.log(text)
  
  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.bone} />
      <skinnedMesh material-color={props.customColors.Hinges} geometry={nodes.Hinges.geometry} material={materials.Hinges} skeleton={nodes.Hinges.skeleton} >
      <Text
        scale={[1, 1, 1]}
        color={props.color} // default
        //anchorX="center" // default
        anchorY="middle" // default
        //position-z={-180}
        text={props.text}
        //position={[50, 50, 10]}
      >
        </Text>
      </skinnedMesh>
      <skinnedMesh material-color={props.customColors.Keys} geometry={nodes.Keys.geometry} material={nodes.Keys.materials} skeleton={nodes.Keys.skeleton} />
      <skinnedMesh  material-color={props.customColors.Piano} geometry={nodes.Piano.geometry} material={nodes.Piano.material} skeleton={nodes.Piano.skeleton} >
      
      </skinnedMesh>
      {props.show && <mesh geometry={nodes.Text.geometry} material={materials['default']} position={[-0.19, 0.97, -0.03]} rotation={[1.34, 0, 0]} scale={0.07} />}
     
      
        
      
    </group>
  )
}

useGLTF.preload('/exemple1.glb')
