/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Violin({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/violin_model.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.violinrestbody.geometry}
        material={materials.restbody}
        position={[-0.23, -0.35, 1.05]}
        scale={0.12}
        material-color={"#fff"}
      />
      <mesh
        geometry={nodes.violintinypiecesSAMEmaterial.geometry}
        material={materials.chords}
        position={[0.27, 4.97, -0.41]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.violin_body.geometry}
        material={materials.body}
        position={[-0.23, -5.53, -0.17]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.violinbowSAMEmaterial.geometry}
        material={materials.stick}
        position={[0.27, 4.97, -0.41]}
        scale={0.12}
      />
    </group>
  );
}

useGLTF.preload("/vio.glb");
